### ISSUE TITLE
报Node.js 16 actions 警告

### ISSUE THREAD

**Issue by dossec** [tech-shrimp/docker_image_pusher#11]
[Pull](https://github.com/dossec/docker_image_pusher/actions/runs/9442336843/job/26004333020)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf, actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by tech-shrimp** [comment]
我升级了下版本
docker/setup-buildx-action@v3
actions/checkout@v4
现在修复了 感谢指正
