### ISSUE TITLE
alist-tvbox怎么拉取

### ISSUE THREAD

**Issue by longtianhgg** [tech-shrimp/docker_image_pusher#13]
大佬，alist-tvbox怎么拉取啊？不会操作，求大佬指点

**Comment by tech-shrimp** [comment]
haroldli/alist-tvbox 
不是先把这个填到images.txt里面，推送到阿里云上
然后这么拉取运行？
docker run -d -p 4567:4567 --restart=always --name=alist-tvbox    {阿里云仓库地址}/{阿里云命名空间}/alist-tvbox

**Comment by Olivesxxxx** [comment]
> haroldli/alist-tvbox 不是先把这个填到images.txt里面，推送到阿里云上 然后这么拉取运行？ docker run -d -p 4567:4567 --restart=always --name=alist-tvbox {阿里云仓库地址}/{阿里云命名空间}/alist-tvbox

笑死我搞了半天谁知道他有两个alist-tvbox，xiaoya-tvbox。我一直以为是我操作问题，想想就好笑
