### ISSUE TITLE
commit changes这一步报错了

### ISSUE THREAD

**Issue by zhoufxiang** [tech-shrimp/docker_image_pusher#15]
#
/
![微信图片_20240610174854](https://github.com/tech-shrimp/docker_image_pusher/assets/31134052/e754f743-7eaf-4efa-b8e2-061a03aa63db)
![微1](https://github.com/tech-shrimp/docker_image_pusher/assets/31134052/5db584c7-bede-44b9-bd1b-fc3d3b8aa3a9)

**Comment by finalparanoia** [comment]
+1，在commit时出错，
platform is 
platform_prefix is 
docker tag caddy ***//caddy
Error parsing reference: "***//caddy" is not a valid repository/tag: invalid reference format

**Comment by tech-shrimp** [comment]
看起来少配置了一个环境变量，是不是name space没配置

**Comment by tech-shrimp** [comment]
<img width="599" alt="image" src="https://github.com/tech-shrimp/docker_image_pusher/assets/154193368/6f44413a-c178-4d93-8f0c-4cf18beb0092">
检查一下这四个变量 看看全不全，首页有视频教程

**Comment by zhoufxiang** [comment]
![微信图片_20240611234928](https://github.com/tech-shrimp/docker_image_pusher/assets/31134052/d22a376b-dc4a-4903-84c9-a481754c336c)
w
![微信图片_20240611234941](https://github.com/tech-shrimp/docker_image_pusher/assets/31134052/e2dceeba-9444-43bb-96ef-244ab9d1f9db)
我看了命名空间配置，配置过了啊，我又重新配了，还是这个报错

**Comment by RayKr** [comment]
出现了同样的错误

**Comment by RayKr** [comment]
> ![微信图片_20240611234928](https://private-user-images.githubusercontent.com/31134052/338656928-d22a376b-dc4a-4903-84c9-a481754c336c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjUxOTksIm5iZiI6MTcxODEyNDg5OSwicGF0aCI6Ii8zMTEzNDA1Mi8zMzg2NTY5MjgtZDIyYTM3NmItZGM0YS00OTAzLTg0YzktYTQ4MTc1NGMzMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE2NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZmVmY2QwY2QyYTIwZjczZDViMzRmMTBjNTIwOTdjOTA1ZWE1YzQ5NjJlYWE3NzMwYzk3MDU4ODVjZmY0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fV3uI62mL6JDGRBNLe1etEqZFKkmroR13uWqUGSU0Ko) w ![微信图片_20240611234941](https://private-user-images.githubusercontent.com/31134052/338656939-e2dceeba-9444-43bb-96ef-244ab9d1f9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjUxOTksIm5iZiI6MTcxODEyNDg5OSwicGF0aCI6Ii8zMTEzNDA1Mi8zMzg2NTY5MzktZTJkY2VlYmEtOTQ0NC00M2JiLTk2ZWYtMjQ0YWI5ZDFmOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE2NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYzFmN2M0YmVjNjU1NjdlN2I5OWM1ODIzNDRkZmVjNGY2Mzg1MjAyMmUyZWM4Njk4MzE5MDU3YWQ3Y2NjM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgh_KYeVH1RAayvFILURL-UTnCkzdrXx6-LM0mp7rxA) 我看了命名空间配置，配置过了啊，我又重新配了，还是这个报错

你的SPACE拼写错了。

**Comment by zhoufxiang** [comment]
> > ![微信图片_20240611234928](https://private-user-images.githubusercontent.com/31134052/338656928-d22a376b-dc4a-4903-84c9-a481754c336c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjUxOTksIm5iZiI6MTcxODEyNDg5OSwicGF0aCI6Ii8zMTEzNDA1Mi8zMzg2NTY5MjgtZDIyYTM3NmItZGM0YS00OTAzLTg0YzktYTQ4MTc1NGMzMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE2NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZmVmY2QwY2QyYTIwZjczZDViMzRmMTBjNTIwOTdjOTA1ZWE1YzQ5NjJlYWE3NzMwYzk3MDU4ODVjZmY0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fV3uI62mL6JDGRBNLe1etEqZFKkmroR13uWqUGSU0Ko) w ![微信图片_20240611234941](https://private-user-images.githubusercontent.com/31134052/338656939-e2dceeba-9444-43bb-96ef-244ab9d1f9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjUxOTksIm5iZiI6MTcxODEyNDg5OSwicGF0aCI6Ii8zMTEzNDA1Mi8zMzg2NTY5MzktZTJkY2VlYmEtOTQ0NC00M2JiLTk2ZWYtMjQ0YWI5ZDFmOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE2NTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYzFmN2M0YmVjNjU1NjdlN2I5OWM1ODIzNDRkZmVjNGY2Mzg1MjAyMmUyZWM4Njk4MzE5MDU3YWQ3Y2NjM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgh_KYeVH1RAayvFILURL-UTnCkzdrXx6-LM0mp7rxA) 我看了命名空间配置，配置过了啊，我又重新配了，还是这个报错
> 
> @zhoufxiang 你的SPACE拼写错了。

多谢，是我大意了
