### ISSUE TITLE
镜像仓库同名的可能性

### ISSUE THREAD

**Issue by A13788899580** [tech-shrimp/docker_image_pusher#28]
真心感谢你项目分享呢！
我不完全确认以下的问题：
拉取镜像-xhofe/alist:latest后，再拉取xiaoyaliu/alist:latest，阿里云的仓库中就只有xiaoyaliu/alist的alist了；
是不是由于阿里云的仓库只有容器名导致的，就把xhofe/alist的镜像给替代了。

**Comment by tech-shrimp** [comment]
把两个都写进文件里就行了

**Comment by A13788899580** [comment]
谢谢你的帮助，我看不到你的图，你的意思是同时把2个镜像都放进去是吧。
但，到了阿里云，名字都是一样的啊，无法直接分辨吧，而且，貌似每个容器的详情并无法判断是具体是那个镜像吧。

**Comment by tech-shrimp** [comment]
程序加了判断 会自动区分，把作者名字拼到前面
