### ISSUE TITLE
镜像版本带sha256值时报错

### ISSUE THREAD

**Issue by anooki-c** [tech-shrimp/docker_image_pusher#33]
docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
镜像名字带sha256值，报错，是不是不能带这个标签啊，这个有办法解决吗
![image](https://github.com/tech-shrimp/docker_image_pusher/assets/55230532/a908951c-d10c-4673-b400-94a08d52a4a6)

**Comment by tech-shrimp** [comment]
感谢 我又改了一版 现在好了应该

**Comment by anooki-c** [comment]
> 感谢 我又改了一版 现在好了应该

可以了，感谢大佬
