### ISSUE TITLE
报错：failed to register layer: write /opt/conda/lib/python3.10/site-packages/torch/lib/libcudnn_cnn_infer.so.8: no space left on device

### ISSUE THREAD

**Issue by Aurora11111** [tech-shrimp/docker_image_pusher#39]
阿里云我的仓库是空的，拉取的镜像大小12G左右，一直报这个错

**Comment by GodenX** [comment]
我也遇到了相似的问题，拉取的这个镜像breakstring/gpt-sovits:latestwrite，报错/var/lib/docker/tmp/GetImageBlob3110843648: no space left on device

**Comment by tech-shrimp** [comment]
> 阿里云我的仓库是空的，拉取的镜像大小12G左右，一直报这个错

我改了下代码，现在应该好了 支持40GB大小镜像了

**Comment by tech-shrimp** [comment]
> 我也遇到了相似的问题，拉取的这个镜像breakstring/gpt-sovits:latestwrite，报错/var/lib/docker/tmp/GetImageBlob3110843648: no space left on device

现在应该没问题了
