### ISSUE TITLE
能否增加自定义名称？

### ISSUE THREAD

**Issue by HandsomeBoy01** [tech-shrimp/docker_image_pusher#44]
例如镜像名称
daprio/dashboard:0.14.0

推送到阿里云 显示的是 dashboard，这样不好，我想自定义一下 可否做到？
例如
docker.io/daprio/dashboard:0.14.0  --name daprio-dashboard:0.14

**Comment by HandsomeBoy01** [comment]
也没必要饿了

**Comment by ocean521** [comment]
或者考虑使用镜像全称，便于区分不同版本的镜像。
