### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by HandsomeBoy01** [tech-shrimp/docker_image_pusher#46]
daprio/dashboard
#linode/dashboard:v2.7.0

例如，我要是只写 第一个 那么在阿里云上面就只会显示 dashboard
我要是两个都写上 才会区分仓库 如
daprio_dashboard
linode_dashboard

希望 只有一个的时候也显示前缀

**Comment by tech-shrimp** [comment]
你好， 我故意这么设计的，主要不想让镜像名字太复杂 如果没有重名就留一个吧。
