### ISSUE TITLE
作者不同，docker名字一样上传到阿里云后会导致覆盖，只有一个了

### ISSUE THREAD

**Issue by lifeifeng2024** [tech-shrimp/docker_image_pusher#7]
例如以下两条Docker镜像上传到阿里云后 只剩下一个，有什么方法能避免吗
joplin/server:latest
vaultwarden/server:latest

**Comment by dossec** [comment]
可以把名字加在镜像前面：比如这样
server/vaultwarden_server:latest 
server/joplin_server:latest 
应该可以的吧

**Comment by Icarusradio** [comment]
> 可以把名字加在镜像前面：比如这样 server/vaultwarden_server:latest server/joplin_server:latest 应该可以的吧

https://github.com/Icarusradio/docker_image_pusher

我自己改的版本，就是按这个方式存储的。不过暂时没法和作者的支持多架构脚本兼容，等我修改完给作者提交一个 PR 吧。

**Comment by wangzhili888** [comment]
xiaoyaliu/alist:latest
xhofe/alist:latest
也是这样，对自己搭建小雅全家桶和阿里网盘的会有冲突

**Comment by tech-shrimp** [comment]
我改了这种情况
xiaoyaliu/alist:latest
xhofe/alist:latest

现在程序会自动判断是否有重名的，如果重名将作者拼在前面
![image](https://github.com/tech-shrimp/docker_image_pusher/assets/154193368/ee14d8ee-08a8-4b2d-b3ac-568aa9c0972b)
